apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/rewrites: "serviceName=echo-service rewrite=/"
    nginx.org/rewrites: "serviceName=tutum-service rewrite=/"
    nginx.org/rewrites: "serviceName=pgadmin rewrite=/"
spec:
  rules:
    - host: newnlb-bb5f7483bbdc7589.elb.ap-southeast-1.amazonaws.com
      http:
        paths:
          - path: /echo
            pathType: Exact
            backend:
              serviceName: echo-service
              servicePort: 80

          - path: /hello
            pathType: Exact
            backend:
              serviceName: tutum-service
              servicePort: 80

          - path: /gpadmin
            pathType: Exact
            backend:
              serviceName: pgadmin
              servicePort: 80