apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/rewrites: "serviceName=pgadmin rewrite=/pgadmin"
    # nginx.org/rewrites: "serviceName=echo rewrite=/"
    # nginx.org/rewrites: "serviceName=tutum rewrite=/"

spec:
  rules:
    - host: newnlb-2acfd26c77b64b7b.elb.ap-southeast-1.amazonaws.com
      http:
        paths:
          - path: /echo
            pathType: Exact
            backend:
              serviceName: echo
              servicePort: 80

          - path: /hello
            pathType: Exact
            backend:
              serviceName: tutum
              servicePort: 80

          - path: /pgadmin
            pathType: Prefix
            backend:
              serviceName: pgadmin
              servicePort: 80