apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: test
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/rewrites: "serviceName=echo-service rewrite=/"
    nginx.org/rewrites: "serviceName=tutum-service rewrite=/"

spec:
  rules:
    - host: my-nlb-76dcee4fcc1292f3.elb.ap-southeast-1.amazonaws.com
      http:
        paths:
          - path: /echo
            pathType: Exact
            backend:
              serviceName: echo-service
              servicePort: 80

          - path: /hello
            pathType: Exact
            backend:
              serviceName: tutum-service
              servicePort: 80
