apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutum
  labels:
    app: tutum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutum
  template:
    metadata:
      labels:
        app: tutum
    spec:
      containers:
        - name: tutum
          image: tutum/hello-world:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: tutum
spec:
  ports:
    - port: 80
  selector:
    app: tutum

# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: ingress-tutum
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.org/rewrites: "serviceName=tutum rewrite=/hello"

# spec:
#   rules:
#     - host: newnlb-2acfd26c77b64b7b.elb.ap-southeast-1.amazonaws.com
#       http:
#         paths:
#           - path: /hello
#             # pathType: Exact
#             backend:
#               serviceName: tutum
#               servicePort: 80
